services:
  scale:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scale-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - delegate_default

networks:
  delegate_default:
    external: true
