services:
  scale:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    container_name: scale-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - delegate_default

networks:
  delegate_default:
    external: true
